services:
  server:
    build:
      context: ./server/
    command: uvicorn main:app --reload --host 0.0.0.0
    networks:
      - qdrant-cluster
    ports:
      - 8000:8000 # For DEV
    volumes:
      - ./server/app:/app

  qdrant-node-1:
    image: qdrant/qdrant:${QDRANT_VERSION}
    container_name: qdrant-node-1
    ports:
      - "6333:6333"  # For DEV 
    networks:
      - qdrant-cluster
    volumes:
      - ./data/node1:/qdrant/storage
      - ./configs/node1.yaml:/qdrant/config/config.yaml
    command:
      ./entrypoint.sh --uri '${QDRANT_BOOTSTRAP_NODE_URI}'
    healthcheck:
      test: ["CMD", "curl", "-f", "${QDRANT_HEALTHCHECK_NODE_URI}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  qdrant-node-2:
    image: qdrant/qdrant:${QDRANT_VERSION}
    container_name: qdrant-node-2
    networks:
      - qdrant-cluster
    volumes:
      - ./data/node2:/qdrant/storage
      - ./configs/node2.yaml:/qdrant/config/config.yaml
    depends_on:
      qdrant-node-1:
        condition: service_started
    command:
      ./entrypoint.sh --bootstrap '${QDRANT_BOOTSTRAP_NODE_URI}'

networks:
  qdrant-cluster:
    driver: bridge
